temp/objects/Acc_Yearly_Revenue_Rollup__c.object
<CustomObject>
    <fields>
        <fullName>Accounts__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Acc Yearly Revenue Rollups</relationshipLabel>
        <relationshipName>Acc_Yearly_Revenue_Rollups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Yearly_Actual_Revenue__c</fullName>
        <label>Yearly Actual Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Yearly_Forecasted_Revenue_Weighted__c</fullName>
        <label>Yearly Forecasted Revenue(Weighted)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Yearly_Forecasted_Revenue__c</fullName>
        <label>Yearly Forecasted Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Acc Yearly Revenue Rollup</label>
    <nameField>
        <label>Acc Yearly Revenue Rollup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Acc Yearly Revenue Rollups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Monthly_Revenue_Rollups__c.object
<CustomObject>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_Actual_Revenue__c</fullName>
        <label>Monthly Actual Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Monthly_Forecasted_Revenue_Weighted__c</fullName>
        <label>Monthly Forecasted Revenue(Weighted)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Monthly_Forecasted_Revenue__c</fullName>
        <label>Monthly Forecasted Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Monthly Revenue Rollups</relationshipLabel>
        <relationshipName>Monthly_Revenue_Rollups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Yearly_Revenue_Rollup__c</fullName>
        <label>Yearly Revenue Rollup</label>
        <referenceTo>Yearly_Revenue_Rollups__c</referenceTo>
        <relationshipLabel>Monthly Revenue Rollups</relationshipLabel>
        <relationshipName>Monthly_Revenue_Rollups</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Monthly Revenue Rollup</label>
    <nameField>
        <label>Monthly Revenue Rollup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Revenue Rollups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>End_Revenue_Date__c</fullName>
        <label>End Revenue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>REVvue_CreatedDate__c</fullName>
        <label>Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>REVvue_RevRecRule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RevRecRule</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>RevRecRules__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>RevRecRules__c</referenceTo>
        <relationshipLabel>Opportunities (RevRecRule)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Revenue_Date__c</fullName>
        <label>Start Revenue Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

temp/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>RevRecRule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RevRecRule</label>
        <referenceTo>RevRecRules__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

temp/objects/RevRecProductFamilySetting__c.object
<CustomObject>
    <fields>
        <fullName>RevRecRule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RevRecRule</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>RevRecRules__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>RevRecRules__c</referenceTo>
        <relationshipLabel>RevRecProductFamilySettings</relationshipLabel>
        <relationshipName>RevRecProductFamilySettings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RevRecProductFamilySetting</label>
    <nameField>
        <label>RevRecProductFamilySetting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RevRecProductFamilySettings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/RevRecRules__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Default_Rule__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default Rule</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Divide_By__c</fullName>
        <label>Divide By</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Divide Evenly Between Start and End Dates</fullName>
                </value>
                <value>
                    <fullName>Divide Evenly Between Start and End Dates - Prorate First and Last Periods</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recognition_Type__c</fullName>
        <label>Recognition Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>RevRecRule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RevRecRules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Yearly_Revenue_Rollups__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Yearly Revenue Rollups</relationshipLabel>
        <relationshipName>Yearly_Revenue_Rollups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Yearly_Actual_Revenue__c</fullName>
        <label>Yearly Actual Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Yearly_Forecasted_Revenue_Weighted__c</fullName>
        <label>Yearly Forecasted Revenue(Weighted)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Yearly_Forecasted_Revenue__c</fullName>
        <label>Yearly Forecasted Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Yearly Revenue Rollup</label>
    <nameField>
        <label>Yearly Revenue Rollup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Yearly Revenue Rollups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/classes/Test_MonthlyRevenueRollupTriggerHelper.cls
@istest
private class Test_MonthlyRevenueRollupTriggerHelper {
    @istest
    Static void myUnitTest1() {
        //Get standard pricbook Id to insert new price booke entery
        Id pricebookId = Test.getStandardPricebookId();
        
        //Insert Accounts
        List<Account> accounts = new List<Account>();
        accounts.add(new Account(Name = 'Test Acc 1'));
        accounts.add(new Account(Name = 'Test Acc 2'));
        insert accounts;
        
        //App Setting Data
        AppRopozSLN__RevRecAppSetting__c appSetting = new AppRopozSLN__RevRecAppSetting__c(Name = 'AppSetting', Certain_date_of_month__c = '28',
                                                                                           AppRopozSLN__Time_of_Month_Selection_Types_tr__c = '1', Time_of_Month_Selection_Types__c = '2');
        insert appSetting;
        
        
        //Default Rule
        RevRecRules__c revRecDefaultRule = new RevRecRules__c(Name = 'Test', Active__c = true, Divide_By__c = '2', 
                                                              AppRopozSLN__Offset_Period__c = 2, AppRopozSLN__Offset_Type__c = 'Start', Default_Rule__c = true,
                                                              Recognition_Type__c = 'Amortize');
        
        insert  revRecDefaultRule;
        
        //Insert RevRecProductFamilySetting__c
        RevRecProductFamilySetting__c prodFamilySetting = new RevRecProductFamilySetting__c(Name = 'Family 1', RevRecRule__c = revRecDefaultRule.Id);
        insert prodFamilySetting;
        
        //List of Product
        List<Product2> products = new List<Product2>();
        products.add(new Product2(Name = 'Test0',  IsActive = true));
        products.add(new Product2(Name = 'Test1',  IsActive = true, Family='Family 1'));
        insert products;
        System.assertEquals(true, products[1].IsActive);
        
        //List of Opportunity
        List<Opportunity> opportunities = new List<Opportunity>();
        opportunities.add(new Opportunity(Name = 'Test' , CloseDate = Date.Today(),StageName = 'Closed Won',  Amount = 1000, Type = 'New Customer', AccountId = accounts[0].Id,End_Revenue_Date__c =  Date.Today().addYears(3) , Start_Revenue_Date__c = Date.Today().addMonths(7),	Probability = 50));
        opportunities.add(new Opportunity(Name = 'Testing1', REVvue_RevRecRule__c=revRecDefaultRule.Id, CloseDate = Date.Today().addMonths(-2), StageName = 'Closed Lost',  Type = 'New Customer', Amount = 1000, REVvue_CreatedDate__c = Date.Today(), Probability = 50, AccountId = accounts[0].Id,End_Revenue_Date__c =  Date.Today().addYears(3) , Start_Revenue_Date__c = Date.Today().addMonths(7)));
        opportunities.add(new Opportunity(Name = 'Testing2' , CloseDate = Date.Today().addMonths(-2), StageName = 'Closed Lost',  Type = 'New Customer', Amount = 1000, REVvue_CreatedDate__c = Date.Today(), AccountId = accounts[0].Id, Probability = 50));
        opportunities.add(new Opportunity(Name = 'Testing3' , CloseDate = Date.Today().addMonths(-2), StageName = 'Closed Lost',  Type = 'New Customer', Amount = 1000, REVvue_CreatedDate__c = Date.Today(), AccountId = accounts[1].Id, Probability = 50));
        
        insert opportunities;
        
        List<Yearly_Revenue_Rollups__c> listOfYearly = new List<Yearly_Revenue_Rollups__c>();
        
        listOfYearly.add(new Yearly_Revenue_Rollups__c(Name  = '2019', Year__c = '2019',Opportunity__c = opportunities[0].Id, Yearly_Actual_Revenue__c = 0, Yearly_Forecasted_Revenue__c = 0, Yearly_Forecasted_Revenue_Weighted__c = 0));
        listOfYearly.add(new Yearly_Revenue_Rollups__c(Name  = '2020', Year__c = '2020', Opportunity__c = opportunities[0].Id, Yearly_Actual_Revenue__c = 0, Yearly_Forecasted_Revenue__c = 0, Yearly_Forecasted_Revenue_Weighted__c = 0));
        listOfYearly.add(new Yearly_Revenue_Rollups__c(Name  = '2021', Year__c = '2021', Opportunity__c = opportunities[1].Id, Yearly_Actual_Revenue__c = 0, Yearly_Forecasted_Revenue__c = 0, Yearly_Forecasted_Revenue_Weighted__c = 0));
        insert listOfYearly;
        System.assertEquals(0, listOfYearly[1].Yearly_Actual_Revenue__c);
        
        List<Monthly_Revenue_Rollups__c> listOfMonthly = new List<Monthly_Revenue_Rollups__c>();
        
        listOfMonthly.add(new Monthly_Revenue_Rollups__c(Name  = '1-2019', Year__c = '2019',Month__c = 1,Yearly_Revenue_Rollup__c =listOfYearly[0].Id, Opportunity__c = opportunities[0].Id, Monthly_Actual_Revenue__c = 0, Monthly_Forecasted_Revenue__c = 0, Monthly_Forecasted_Revenue_Weighted__c = 0));
        listOfMonthly.add(new Monthly_Revenue_Rollups__c(Name  = '1-2019', Year__c = '2019',Month__c = 1,Yearly_Revenue_Rollup__c =listOfYearly[1].Id, Opportunity__c = opportunities[0].Id, Monthly_Actual_Revenue__c = 0, Monthly_Forecasted_Revenue__c = 0, Monthly_Forecasted_Revenue_Weighted__c = 0));
        listOfMonthly.add(new Monthly_Revenue_Rollups__c(Name  = '1-2019', Year__c = '2019',Month__c = 1,Yearly_Revenue_Rollup__c =listOfYearly[0].Id, Opportunity__c = opportunities[0].Id, Monthly_Actual_Revenue__c = 0, Monthly_Forecasted_Revenue__c = 0, Monthly_Forecasted_Revenue_Weighted__c = 0));
        insert listOfMonthly;
        
        List<Acc_Yearly_Revenue_Rollup__c> listOfAccYearlyIDs = new List<Acc_Yearly_Revenue_Rollup__c>();
        listOfAccYearlyIDs.add(new Acc_Yearly_Revenue_Rollup__c(Name  = '2019', Year__c = '2019',Accounts__c = accounts[0].Id, Yearly_Actual_Revenue__c = 0, Yearly_Forecasted_Revenue__c = 0, Yearly_Forecasted_Revenue_Weighted__c = 0));
        listOfAccYearlyIDs.add(new Acc_Yearly_Revenue_Rollup__c(Name  = '2020', Year__c = '2020',Accounts__c = accounts[1].Id, Yearly_Actual_Revenue__c = 0, Yearly_Forecasted_Revenue__c = 0, Yearly_Forecasted_Revenue_Weighted__c = 0));
        listOfAccYearlyIDs.add(new Acc_Yearly_Revenue_Rollup__c(Name  = '2021', Year__c = '2021',Accounts__c = accounts[0].Id, Yearly_Actual_Revenue__c = 0, Yearly_Forecasted_Revenue__c = 0, Yearly_Forecasted_Revenue_Weighted__c = 0));
		insert listOfAccYearlyIDs;
        delete listOfAccYearlyIDs[0];
        System.assertEquals(3, listOfAccYearlyIDs.size());
        
       List<Monthly_Revenue_Rollups__c> qureyMonthly = [Select Id, Name, Year__c, Month__c, Monthly_Actual_Revenue__c, Monthly_Forecasted_Revenue__c FROM Monthly_Revenue_Rollups__c];
        //System.assert(false,qureyMonthly);
        qureyMonthly[0].Monthly_Actual_Revenue__c = 50.00;
        update qureyMonthly;
        delete qureyMonthly[1];        
    }
}