temp/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>TCV_Actual__c</fullName>
        <label>TCV Actual</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

temp/objects/RevRecOpportunityLineItem__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Revenue Opportunity Line Items</relationshipLabel>
        <relationshipName>RevRecOpportunityLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>RevRecOpportunityLineItem</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RevRecOpportunityLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/RevRecOpportunityLineItemSchedule__c.object
<CustomObject>
    <description>RevRec OpportunityLineItemSchedule</description>
    <fields>
        <fullName>RevRecOpportunityLineItem__c</fullName>
        <label>RevRecOpportunityLineItem</label>
        <referenceTo>RevRecOpportunityLineItem__c</referenceTo>
        <relationshipLabel>RevRecOpportunityLineItemSchedules</relationshipLabel>
        <relationshipName>RevRecOpportunityLineItemSchedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>RevRecOpportunityLineItemSchedule</label>
    <nameField>
        <label>RevRecOpportunityLineItemSchedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RevRecOpportunityLineItemSchedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/classes/RevRecOLIScheduleTriggerHelper.cls
/**
*  Description     :   This is the helper class for RevRecOLIScheduleTriggerHelper.
*
*  Created Date    :   04/11/2020
*
*  Created By      :   
*
*  Version         :   V_1.0
*
**/
public without  sharing class RevRecOLIScheduleTriggerHelper {
    
    /**
    *  @description    :   This method is used to find the related Rule criteria and stamp related rule on the Product.    
    *
    *  @args           :   Trigger.New, Trigger.oldMap
    *
    *  @return         :   
    **/
    public static void calculateRollupData (List<RevRecOpportunityLineItemSchedule__c> newRROLISches) {
        
        constants.IS_BY_PASS_SCHEDULES_TRIGGER = false;
        //Variable initialization
        Set<Id> setRROLIIds = new Set<Id>();	//Set of RevRecOpportunityLineItem Id
        Boolean isMultiCurrencyEnabled = UserInfo.isMultiCurrencyOrganization();
        String opportunityId;
        
        //Check if RevRecOpportunityLineItemSchedule list has value
        if(newRROLISches.size() > 0) {
            
            //Loop over newly inserted schedules
            for(RevRecOpportunityLineItemSchedule__c rrOLISche : newRROLISches)
                setRROLIIds.add(rrOLISche.RevRecOpportunityLineItem__c);
            
            //Loop to fetch RevRecOpportunityLineItem
            for(RevRecOpportunityLineItem__c rrOLI : [SELECT Id, Opportunity__c FROM RevRecOpportunityLineItem__c 
                                                      WHERE Id IN: setRROLIIds]) {
                opportunityId = rrOLI.Opportunity__c;
            }
           
            String queryOpp = '';
            
            if(opportunityId != null) {
                
                //Check if, multicurrency is enable
                if(!isMultiCurrencyEnabled)
                    queryOpp += 'SELECT Id, name, CloseDate , TCV_Actual__c, Probability FROM Opportunity  WHERE Id = \''+ opportunityId +'\' LIMIT 1 FOR UPDATE';
                else
                    queryOpp += 'SELECT Id, name, CurrencyIsoCode, CloseDate , TCV_Actual__c, Probability FROM Opportunity WHERE Id = \''+ opportunityId +'\' LIMIT 1 FOR UPDATE';
            }
             
            //Database.query for opp
            List<Opportunity> listOfallOpp = database.query(queryOpp);
             
            if(!system.isBatch() && listOfallOpp.size() > 0) {
                //Calling batch...
                 Batch_MassRollUpRevenueCalculation massRollupCalBatch = new Batch_MassRollUpRevenueCalculation(listOfallOpp);
                
                 //Parameters of ExecuteBatch(context,BatchSize)
                 database.executebatch(massRollupCalBatch,1);
                
            }
        }
        
    }
}