temp/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>REVvue_CreatedDate__c</fullName>
        <label>Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>REVvue_CurrencyType__c</fullName>
        <inlineHelpText>Put currency ISO code to calculate the converted amount(USD,GBP...).</inlineHelpText>
        <label>Currencey Type</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REVvue_CurrentGenerators__c</fullName>
        <label>Current Generator(s)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REVvue_DeliveryInsStatus__c</fullName>
        <label>Delivery/Installation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Yet to begin</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>REVvue_ExecMassCalc__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Execute Mass Calculation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>REVvue_InitialOpp__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Initial Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities (Initial Opportunity)</relationshipLabel>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>REVvue_MainCompetitors__c</fullName>
        <label>Main Competitor(s)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REVvue_OrderNumber__c</fullName>
        <label>Order Number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REVvue_ParentOpp__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities (Parent Opportunity)</relationshipLabel>
        <relationshipName>Opportunities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>REVvue_RevRecRule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RevRecRule</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>RevRecRules__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>RevRecRules__c</referenceTo>
        <relationshipLabel>Opportunities (RevRecRule)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>REVvue_RuleAssignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rule Assignment</label>
        <referenceTo>Rule_Assignment__c</referenceTo>
        <relationshipLabel>Opportunities (Rule Assignment)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>REVvue_TotalDeferred__c</fullName>
        <label>Total Deferred</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>REVvue_TotalDeferredwei__c</fullName>
        <label>Total Deferred weighted</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>REVvue_TotalForecasted__c</fullName>
        <label>Total Forecasted</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>REVvue_TotalForecastedwei__c</fullName>
        <label>Total Forecasted weighted</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>REVvue_TotalOpportunity__c</fullName>
        <label>Total Opportunity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>REVvue_TotalRecognized__c</fullName>
        <label>Total Recognized</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>REVvue_TotalRecognizedwei__c</fullName>
        <label>Total Recognized weighted</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>REVvue_TotalResidual__c</fullName>
        <label>Total Residual</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>REVvue_TotalResidualwei__c</fullName>
        <label>Total Residual weighted</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>REVvue_Total_Opp_wei__c</fullName>
        <label>Total Opportunity weighted</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>REVvue_TrackingNumber__c</fullName>
        <label>Tracking Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
</CustomObject>

temp/objects/Rule_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>RevRecRule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RevRecRule</label>
        <referenceTo>RevRecRules__c</referenceTo>
        <relationshipLabel>Rule Assignments</relationshipLabel>
        <relationshipName>Rule_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rule Assignment</label>
    <nameField>
        <label>Rule Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rule Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Batch_UpdateOpportunityREVvueFields.cls
/**
 *  Description     :   Batch is used to update opportunity data to newly created fields prefixed with REVvue.
 *
 *  Created By      :
 *
 *  Created Date    :   09/12/2018
 *
 *  Version         :   V_1.0
 *
 *  Revision Logs   : 
 *      
 **/
global class Batch_UpdateOpportunityREVvueFields implements Database.Batchable<sObject> {

    //Start method
    global Database.QueryLocator start(Database.BatchableContext BC) {

        String query = 'SELECT';

        Map<String, Schema.SObjectField> objectFields = Schema.getGlobalDescribe().get('Opportunity').getDescribe().fields.getMap();
    
        for(String s : objectFields.keySet()) {   query += ' ' + s + ',';}
        
        // Strip off the last comma if it exists.
        if (query.subString(query.Length()-1,query.Length()) == ','){    query = query.subString(0,query.Length()-1);}
        
        query += ' FROM Opportunity';
        
        System.debug('@@@@ query ' +query);
        
        //query through the lead
        return Database.getQueryLocator(query);
    }
    
    //Execute method
    global void execute(Database.BatchableContext BC, List<Opportunity> opportunities) {
       
        //List to hold opportunities to be updated
        List<Opportunity> opportunitiesToBeUpdated = new List<Opportunity>();
        
        //Check for size
        if(opportunities.size() > 0) {
            //Loop over querried opportunities
            for(Opportunity opp : opportunities) {
                
                //Set flag to false
                Boolean isChange = false;
        
        		//Check for any change 
                /*if(opp.Created_Date__c != null && opp.REVvue_CreatedDate__c != opp.Created_Date__c) {
                	isChange = true;
                    opp.REVvue_CreatedDate__c = opp.Created_Date__c;
                }
                    
                if(opp.Currencey_Type__c != null && opp.REVvue_CurrencyType__c != opp.Currencey_Type__c) {
                    isChange = true;
                    opp.REVvue_CurrencyType__c = opp.Currencey_Type__c;
                }
                    
                if(opp.CurrentGenerators__c != null && opp.REVvue_CurrentGenerators__c != opp.CurrentGenerators__c) {
                    isChange = true;
                    opp.REVvue_CurrentGenerators__c = opp.CurrentGenerators__c;
                }
                    
                if(opp.DeliveryInstallationStatus__c != null && opp.REVvue_DeliveryInsStatus__c != opp.DeliveryInstallationStatus__c) {
                    isChange = true;
                    opp.REVvue_DeliveryInsStatus__c = opp.DeliveryInstallationStatus__c;
                }
                    
                if(opp.Execute_Mass_Calculation__c != null && opp.REVvue_ExecMassCalc__c != opp.Execute_Mass_Calculation__c) {
                    isChange = true;
                    opp.REVvue_ExecMassCalc__c = opp.Execute_Mass_Calculation__c;
                }
                    
                if(opp.Initial_Opportunity__c != null && opp.REVvue_InitialOpp__c != opp.Initial_Opportunity__c) {
                    isChange = true;
                    opp.REVvue_InitialOpp__c = opp.Initial_Opportunity__c;
                }
                    
                if(opp.MainCompetitors__c != null && opp.REVvue_MainCompetitors__c != opp.MainCompetitors__c) {
                    isChange = true;
                    opp.REVvue_MainCompetitors__c = opp.MainCompetitors__c;
                }
                    
                if(opp.OrderNumber__c != null && opp.REVvue_OrderNumber__c != opp.OrderNumber__c) {
                	isChange = true; 
                    opp.REVvue_OrderNumber__c = opp.OrderNumber__c;
            	}
                    
                if(opp.Parent_Opportunity__c != null && opp.REVvue_ParentOpp__c != opp.Parent_Opportunity__c) {
                    isChange = true;
                    opp.REVvue_ParentOpp__c = opp.Parent_Opportunity__c;
                }
                    
                if(opp.RevRecRule__c != null && opp.REVvue_RevRecRule__c != opp.RevRecRule__c) {
                    isChange = true;
                    opp.REVvue_RevRecRule__c = opp.RevRecRule__c;
                }
                    
                if(opp.Rule_Assignment__c != null && opp.REVvue_RuleAssignment__c != opp.Rule_Assignment__c) {
                    isChange = true;
                    opp.REVvue_RuleAssignment__c = opp.Rule_Assignment__c;
                }
                    
                if(opp.TotalDeferred__c != null && opp.REVvue_TotalDeferred__c != opp.TotalDeferred__c) { 
                    isChange = true;
                    opp.REVvue_TotalDeferred__c = opp.TotalDeferred__c;
                }
                
                if(opp.Total_Deferred_weighted__c != null && opp.REVvue_TotalDeferredwei__c != opp.Total_Deferred_weighted__c) { 
                    isChange = true;
                    opp.REVvue_TotalDeferredwei__c = opp.Total_Deferred_weighted__c;
                }
                    
                if(opp.TotalForecasted__c != null && opp.REVvue_TotalForecasted__c != opp.TotalForecasted__c) {
                    isChange = true;
                    opp.REVvue_TotalForecasted__c = opp.TotalForecasted__c;
                }
                    
                if(opp.Total_Forecasted_weighted__c != null && opp.REVvue_TotalForecastedwei__c != opp.Total_Forecasted_weighted__c) {
                    isChange = true;
                    opp.REVvue_TotalForecastedwei__c = opp.Total_Forecasted_weighted__c;
                }
                    
                if(opp.TotalOpportunity__c != null && opp.REVvue_TotalOpportunity__c != opp.TotalOpportunity__c) {
                    isChange = true;
                    opp.REVvue_TotalOpportunity__c = opp.TotalOpportunity__c;
                }
                    
                if(opp.Total_Opportunity_weighted__c != null && opp.REVvue_Total_Opp_wei__c != opp.Total_Opportunity_weighted__c) {
                    isChange = true;
                    opp.REVvue_Total_Opp_wei__c = opp.Total_Opportunity_weighted__c;
                }
                    
                if(opp.TotalRecognized__c != null && opp.REVvue_TotalRecognized__c != opp.TotalRecognized__c) {
                    isChange = true;
                    opp.REVvue_TotalRecognized__c = opp.TotalRecognized__c;
                }
                    
                if(opp.Total_Recognized_weighted__c != null && opp.REVvue_TotalRecognizedwei__c != opp.Total_Recognized_weighted__c) { 
                    isChange = true;
                    opp.REVvue_TotalRecognizedwei__c = opp.Total_Recognized_weighted__c;
                }
                    
                if(opp.TotalResidual__c != null && opp.REVvue_TotalResidual__c != opp.TotalResidual__c) { 
                    isChange = true;
                    opp.REVvue_TotalResidual__c = opp.TotalResidual__c;
                }
                    
                if(opp.Total_Residual_weighted__c != null && opp.REVvue_TotalResidualwei__c != opp.Total_Residual_weighted__c) { 
                    isChange = true;
                    opp.REVvue_TotalResidualwei__c = opp.Total_Residual_weighted__c;
                }
                    
                if(opp.TrackingNumber__c != null && opp.REVvue_TrackingNumber__c != opp.TrackingNumber__c) {
                    isChange = true;
                    opp.REVvue_TrackingNumber__c = opp.TrackingNumber__c;
            	}*/
            	
            	if(isChange) 
            		opportunitiesToBeUpdated.add(opp);
            }
        }
        
        //Update Opporutnity
        if(opportunitiesToBeUpdated.size() > 0)
        	update opportunitiesToBeUpdated;
    }
    
    //Finish method
    global void finish(Database.BatchableContext BC) {}
}