temp/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>RevRecOpportunityLineItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RevRecOpportunityLineItem</label>
        <referenceTo>RevRecOpportunityLineItem__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

temp/objects/RevRecOpportunityLineItem__c.object
<CustomObject>
    <fields>
        <fullName>CalculatedAt__c</fullName>
        <label>Date Calculated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DeferredRev__c</fullName>
        <label>Deferred Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OpportunityLineItemId__c</fullName>
        <label>OpportunityLineItemId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductName__c</fullName>
        <label>ProductName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecognizedRev__c</fullName>
        <label>Recognized Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ResidualAmount__c</fullName>
        <label>Residual Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalRev__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>RevRecOpportunityLineItem</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RevRecOpportunityLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/RevRecProductRule__c.object
<CustomObject>
    <fields>
        <fullName>Divide_By__c</fullName>
        <label>Divide By</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Divided evenly between the start and end dates</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Initial_Amount_Type__c</fullName>
        <label>Initial Amount Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amount</fullName>
                </value>
                <value>
                    <fullName>Percent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Initial_Amount__c</fullName>
        <label>Initial Amount:</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_Manual_Update__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Manual Update</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Milestone_Type__c</fullName>
        <label>RevenueType</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>amount</fullName>
                </value>
                <value>
                    <fullName>qty</fullName>
                </value>
                <value>
                    <fullName>percent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Offset_Period__c</fullName>
        <label>Offset Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Offset_Type__c</fullName>
        <label>Offset Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Start</fullName>
                </value>
                <value>
                    <fullName>Period</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <label>Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                    <default>true</default>
                    <label>Monthly</label>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
                <value>
                    <fullName>Daily</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Period_or_Exact_Days__c</fullName>
        <label>Period or Exact Days</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>By Period</fullName>
                </value>
                <value>
                    <fullName>By Exact Days</fullName>
                </value>
                <value>
                    <fullName>By Percentage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Projected_Amount__c</fullName>
        <label>Projected Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Projected_Qty__c</fullName>
        <label>Projected Qty</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recognition_Type__c</fullName>
        <label>Recognition Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Residual_Amount_Type__c</fullName>
        <label>Residual Amount Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amount</fullName>
                </value>
                <value>
                    <fullName>Percent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Residual_Amount__c</fullName>
        <label>Residual Amount:</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RevRecOpportunityLineItem__c</fullName>
        <label>RevRecOpportunityLineItem</label>
        <referenceTo>RevRecOpportunityLineItem__c</referenceTo>
        <relationshipLabel>RevRecProductRules</relationshipLabel>
        <relationshipName>RevRecProductRules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Period__c</fullName>
        <label>Total Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>RevRecProductRule</label>
    <nameField>
        <label>RevRecProductRule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RevRecProductRules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/RevRecProductRuleMilestone__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Amount__c</fullName>
        <label>Actual Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Actual_Qty__c</fullName>
        <label>Actual Qty</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Projected_Amount__c</fullName>
        <label>Projected Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Projected_Qty__c</fullName>
        <label>Projected Qty</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RevRecProductRule__c</fullName>
        <label>RevRecProductRule</label>
        <referenceTo>RevRecProductRule__c</referenceTo>
        <relationshipLabel>RevRecProductRuleMilestones</relationshipLabel>
        <relationshipName>RevRecProductRuleMilestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>RevRecProductRuleMilestone</label>
    <nameField>
        <label>RevRecProductRuleMilestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RevRecProductRuleMilestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/classes/RevRecProductRuleMilestoneTriggerHelper.cls
/**
 *  Description         :   This is a handler for OpportunityLineItem trigger.
 *
 *  Created By          :   Bill Feeheley
 *
 *  Created Date        :   11/09/2016
 *
 *  Version             :   V_1.0 
 *
 *  Revision Log        :   V_1.0 - Created 
 **/
 public with sharing class RevRecProductRuleMilestoneTriggerHelper {
  
  /**
     *  @purpose    :   This method is used to set milestone checkbox if it is an manual update.
     *
     *  @return     :   
     *
     *  @args       :   Trigger.NewLlist of RevRecProductRuleMilestone__c), Trigger.Old (Map of Id and RevRecProductRuleMilestone)
     **/
    public static void setOverriddenRuleManualUpdateCheckBoxValue(List<RevRecProductRuleMilestone__c> newRRPRMilestones, Map<Id, RevRecProductRuleMilestone__c> mapOldRRPRMilestone) {
    
    	//Variable to hold id of overridden rule
    	Map<Id, Boolean> mapIOverriddenRuleIdWithUpdateFlag = new Map<Id, Boolean>();

    	//Loop over new milestone values
    	for(RevRecProductRuleMilestone__c milestone: newRRPRMilestones) {
    		
    		//Flag to check is update or not
    		Boolean isUpdateCheckBox = false;
    	
    		//Check, if blank update
    		if(milestone.Actual_Amount__c != mapOldRRPRMilestone.get(milestone.Id).Actual_Amount__c || milestone.Actual_Qty__c != mapOldRRPRMilestone.get(milestone.Id).Actual_Qty__c
    		  || milestone.Projected_Amount__c != mapOldRRPRMilestone.get(milestone.Id).Projected_Amount__c || milestone.Projected_Qty__c != mapOldRRPRMilestone.get(milestone.Id).Projected_Qty__c)
    		  	isUpdateCheckBox = true;	//Setting flag
    		
    		//Putting values in map
    		mapIOverriddenRuleIdWithUpdateFlag.put(milestone.RevRecProductRule__c, isUpdateCheckBox);	  
    	}
    	
    	//Check, if manual update found
    	if(mapIOverriddenRuleIdWithUpdateFlag.size() > 0) {
    	
    		//Fetching overridden rule 
    		List<RevRecProductRule__c> overriddenRules = [Select Id, Is_Manual_Update__c from RevRecProductRule__c where Id IN: mapIOverriddenRuleIdWithUpdateFlag.keySet()];
    		
    		//Check, if overridden rule found
    		if(overriddenRules.size() > 0) {
    			
    			//Loop over overridden rule
    			for(RevRecProductRule__c overriddenrule : overriddenRules)
    				overriddenrule.Is_Manual_Update__c = mapIOverriddenRuleIdWithUpdateFlag.get(overriddenrule.Id);	//Setting checkbox value
    			
    			update overriddenRules;	// updating overridden rule 
    		}
    	}
    }
     
   	public static void oppCalculation(List<RevRecProductRuleMilestone__c> newRROverriddenMiles, List<RevRecProductRuleMilestone__c> oldRROverriddenMiles) {
        
        String oppId = '';
        String msg = '';
        List<Id> ids = new List<Id>();
        
        if (Trigger.isUpdate || Trigger.isInsert) {
            for(RevRecProductRuleMilestone__c item : newRROverriddenMiles)
                    ids.add(item.RevRecProductRule__c);
        }else if(Trigger.isDelete) {
            for(RevRecProductRuleMilestone__c item : oldRROverriddenMiles)
                    ids.add(item.RevRecProductRule__c);
        }
        //Only one overrideRuleId is needed here 
        if(ids.size() > 0) {          
            RevRecProductRule__c overrideRule = [SELECT Id, name, Divide_By__c, initial_amount__c, initial_amount_type__c, Offset_Period__c,  offset_type__c,Period__c, 
                            Period_or_Exact_Days__c, Recognition_Type__c, MileStone_Type__c, Residual_Amount__c, Residual_Amount_Type__c, Start_Date__c, End_Date__c,  Total_Period__c, RevRecOpportunityLineItem__c
                            FROM RevRecProductRule__c WHERE id = : ids[0]];
    
            List<OpportunityLineItem> olis = [SELECT Id, OpportunityId, RevRecOpportunityLineItem__c, RevRecOpportunityLineItem__r.Id,
                            RevRecOpportunityLineItem__r.OpportunityLineItemId__c, RevRecOpportunityLineItem__r.DeferredRev__c,
                            RevRecOpportunityLineItem__r.TotalRev__c, RevRecOpportunityLineItem__r.RecognizedRev__c,
                            RevRecOpportunityLineItem__r.CalculatedAt__c, RevRecOpportunityLineItem__r.ResidualAmount__c,
                            RevRecOpportunityLineItem__r.ProductName__c
                            FROM OpportunityLineItem WHERE RevRecOpportunityLineItem__c != null 
                            AND RevRecOpportunityLineItem__c = :overrideRule.RevRecOpportunityLineItem__c];
            
            if (olis !=null && olis.size() > 0)
        		oppId = olis[0].OpportunityId;
        	else {
                msg += 'Wrong line item. ';
                return;
            }
            
            if(oppId.length() > 0) {
                try {
                     //Code added - 01/31/2015 - By pass the code looping
                     if(overrideRule.Recognition_Type__c == constants.RULE_RECOGNITION_TYPE_AMORTIZE_MILESTONE ||
                        overrideRule.Recognition_Type__c == 'Milestone')
                        return;
                    
                    RevRecUtil util = new RevRecUtil();
                    RevRecUtilHelper utilHelper = new RevRecUtilHelper();
                    utilHelper.Cleanup();
                    util.EvaluateRevRecScheduleForOpportunity(oppId);
                } catch (Exception exp) { System.debug('Exception...@@@'+exp);}
            }
        }
    }
}