temp/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>REVvue_RevRecRule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RevRecRule</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>RevRecRules__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>RevRecRules__c</referenceTo>
        <relationshipLabel>Opportunities (RevRecRule)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

temp/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>RevRecOpportunityLineItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RevRecOpportunityLineItem</label>
        <referenceTo>RevRecOpportunityLineItem__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

temp/objects/RevRecProductRule__c.object
<CustomObject>
    <fields>
        <fullName>Amortize_By__c</fullName>
        <label>Amortize By-Delete</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amount</fullName>
                </value>
                <value>
                    <fullName>qty</fullName>
                    <default>true</default>
                    <label>qty</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Divide_By__c</fullName>
        <label>Divide By</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Divided evenly between the start and end dates</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Enable_Manual_Forecast__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Manual Forecast</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Percentage__c</fullName>
        <label>End Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Forecast_With_Zero_Value__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Forecast With Zero Value</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Initial_Amount_Type__c</fullName>
        <label>Initial Amount Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amount</fullName>
                </value>
                <value>
                    <fullName>Percent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Initial_Amount__c</fullName>
        <label>Initial Amount:</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_Split_Categories__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Split Categories</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Milestone_Type__c</fullName>
        <label>RevenueType</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>amount</fullName>
                </value>
                <value>
                    <fullName>qty</fullName>
                </value>
                <value>
                    <fullName>percent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Offset_Period__c</fullName>
        <label>Offset Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Offset_Type__c</fullName>
        <label>Offset Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Start</fullName>
                </value>
                <value>
                    <fullName>Period</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Period_or_Exact_Days__c</fullName>
        <label>Period or Exact Days</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>By Period</fullName>
                </value>
                <value>
                    <fullName>By Exact Days</fullName>
                </value>
                <value>
                    <fullName>By Percentage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recognition_Type__c</fullName>
        <label>Recognition Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Residual_Amount_Type__c</fullName>
        <label>Residual Amount Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amount</fullName>
                </value>
                <value>
                    <fullName>Percent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Residual_Amount__c</fullName>
        <label>Residual Amount:</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RevRecOpportunityLineItem__c</fullName>
        <label>RevRecOpportunityLineItem</label>
        <referenceTo>RevRecOpportunityLineItem__c</referenceTo>
        <relationshipLabel>RevRecProductRules</relationshipLabel>
        <relationshipName>RevRecProductRules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Revenue_Recognition_End_Date__c</fullName>
        <label>Revenue Recognition End Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Revenue_Recognition_Start_Date__c</fullName>
        <label>Revenue Recognition Start Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Percentage__c</fullName>
        <label>Start Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>RevRecProductRule</label>
    <nameField>
        <label>RevRecProductRule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RevRecProductRules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/RevRecRules__c.object
<CustomObject>
    <fields>
        <fullName>Divide_By__c</fullName>
        <label>Divide By</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Divide Evenly Between Start and End Dates</fullName>
                </value>
                <value>
                    <fullName>Divide Evenly Between Start and End Dates - Prorate First and Last Periods</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Enable_Manual_Forecast__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Manual Forecast</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Percentage__c</fullName>
        <label>End Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Forecast_With_Zero_Value__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Forecast with Zero Value</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Initial_Amount_Type__c</fullName>
        <label>Initial Amount Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amount</fullName>
                </value>
                <value>
                    <fullName>Percent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Initial_Amount__c</fullName>
        <label>Initial Amount:</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_Split_Categories__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Split Categories</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Milestone_Type__c</fullName>
        <label>Revenue Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>amount</fullName>
                </value>
                <value>
                    <fullName>qty</fullName>
                </value>
                <value>
                    <fullName>percent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Offset_Period__c</fullName>
        <label>Offset Period:</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Offset_Type__c</fullName>
        <label>Offset Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Start</fullName>
                </value>
                <value>
                    <fullName>Period</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Period_or_Exact_Days__c</fullName>
        <label>Period or Exact Days</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>By Period</fullName>
                </value>
                <value>
                    <fullName>By Exact Days</fullName>
                </value>
                <value>
                    <fullName>By Percentage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recognition_Type__c</fullName>
        <label>Recognition Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Residual_Amount_Type__c</fullName>
        <label>Residual Amount Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amount</fullName>
                </value>
                <value>
                    <fullName>Percent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Residual_Amount__c</fullName>
        <label>Residual Amount:</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Revenue_Recognition_End_Date__c</fullName>
        <label>Revenue Recognition End Date</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ship Date</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Revenue_Recognition_Start_Date__c</fullName>
        <label>Revenue Recognition Start Date</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ship Date</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Percentage__c</fullName>
        <label>Start Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>RevRecRule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RevRecRules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OverriddenRuleInsertionOnOpptyLevel.cls
/**
 *  Description     :   This class is used to create overridden rule on opportunity level.
 *
 *  Created Date    :   07/19/2016 
 *
 *  Version         :   V_1.0
 *
 *  Revision Log    :   V_1.0 - Created 
**/
public class OverriddenRuleInsertionOnOpptyLevel {
    
    //Map is used to hold the field permission
    Static Map<String, Schema.DescribeFieldResult> mapfieldProdRuleResult = Utility.getFieldPermissions('RevRecProductRule__c');
    
    /** 
     *  @description        :   Method to upsert overridden rule on opportunity level.
     *
     *  @args               :   Opportunity, Map<Id, OpportunityLineItem>, Set<Id>(revrecopportunitylineitem id's)
     *
     *  @return             :   String
     **/
    public String overriddenRuleOnOpptyLevel(Opportunity oppty, Map<Id, OpportunityLineItem> mapRuleIdWithOLI, Set<Id> revRecOLIIds) {
        
        //Variable 
        String msg = '';
        
        Opportunity theOppty = (Opportunity)RevRecHelper.SelectAllFieldsForObject('Opportunity', oppty.Id);
        
        //Fetching rule detail to create overridden rule
        List<RevRecRules__c> theRules = [Select Residual_Amount__c, Residual_Amount_Type__c, initial_amount__c, initial_amount_type__c,
                                  Recognition_Type__c, offset_type__c, Divide_By__c, name, Period_or_Exact_Days__c,
                                  Milestone_Type__c, Start_Percentage__c, End_Percentage__c, Is_Split_Categories__c, Offset_Period__c,
                                  Revenue_Recognition_Start_Date__c, Revenue_Recognition_End_Date__c, Enable_Manual_Forecast__c, 
                                  Forecast_With_Zero_Value__c
                                  From RevRecRules__c where Id =: oppty.REVvue_RevRecRule__c AND Is_Split_Categories__c = false];
        
        //List to upsert overridden rule
        List<RevRecProductRule__c> overrideRuleToBeUpserted = new List<RevRecProductRule__c>();
        
        if(theRules.size() > 0) {
            
            //Loop to fetch revrecopportunitylineitem id's
            for(Id revRecId : revRecOLIIds) {
                
                //Overridden rule instance
                RevRecProductRule__c overrideRule = new RevRecProductRule__c();
                
                OpportunityLineItem theOLI = (OpportunityLineItem)RevRecHelper.SelectAllFieldsForObject('OpportunityLineItem', mapRuleIdWithOLI.get(revRecId).Id);
                Product2 theProduct2 = (Product2)RevRecHelper.SelectAllFieldsForObject('Product2', mapRuleIdWithOLI.get(revRecId).PricebookEntry.product2.Id);
                Contract theContract = (Contract)RevRecHelper.SelectAllFieldsForObject('Contract', theOppty.ContractId);
                
                //Get the start date and end date
                String RevRecStartDateField = theRules[0].Revenue_Recognition_Start_Date__c;
                String RevRecEndDateField = theRules[0].Revenue_Recognition_End_Date__c;
                Date startDate = null;
                Date endDate = null;
                
                //Check if, start date is needed
                if(theRules[0].Recognition_Type__c != Constants.RULE_RECOGNITION_TYPE_MILESTONE && 
                   theRules[0].Recognition_Type__c != Constants.RULE_RECOGNITION_TYPE_BLENDED_REVENUE) {
                    
                    //Fetching date
                    if (RevRecStartDateField != null && RevRecStartDateField.contains(constants.SOBJECT_OPPORTUNITY)){
                    	if(RevRecStartDateField.contains(constants.SOBJECT_LINE_ITEM_COLON)) {
	                        String fieldName = RevRecStartDateField.subString(20, RevRecStartDateField.length()); 
	                        startDate = (Date)theOLI.get(fieldName);
                    	} else {
	                        String fieldName = RevRecStartDateField.subString(12, RevRecStartDateField.length()); 
	                        startDate = (Date)theOppty.get(fieldName);
                    	}
                    } else if (RevRecStartDateField != null && RevRecStartDateField.contains(constants.SOBJECT_LINE_ITEM_COLON)) {
                        String fieldName = RevRecStartDateField.subString(8, RevRecStartDateField.length());
                        startDate = (Date)theProduct2.get(fieldName);
                    } else if (RevRecStartDateField != null && RevRecStartDateField.contains(constants.SOBJECT_CONTRACT_COLON)) {
                        String fieldName = RevRecStartDateField.subString(9, RevRecStartDateField.length());
                        startDate = (Date)theContract.get(fieldName);
                    }
                    
                    //Assigning date
                    if (theRules[0].Recognition_Type__c == Constants.RULE_RECOGNITION_TYPE_SINGLE_TRANSACTION) {
                        endDate = startDate;
                    } else {
                        if (RevRecEndDateField != null && RevRecEndDateField.contains(constants.SOBJECT_OPPORTUNITY)) {
                        	if(RevRecEndDateField.contains(constants.SOBJECT_LINE_ITEM_COLON)) {
                        		String fieldName = RevRecEndDateField.subString(20, RevRecEndDateField.length());
                            	endDate = (Date)theOLI.get(fieldName);	
                        	}
                        	else {
                        		string fieldName = RevRecEndDateField.subString(12, RevRecEndDateField.length());
                            	endDate = (Date)theOppty.get(fieldName);
                        	}
                        } else if (RevRecEndDateField != null && RevRecEndDateField.contains(constants.SOBJECT_LINE_ITEM_COLON)){
                            string fieldName = RevRecEndDateField.subString(8, RevRecEndDateField.length());
                            endDate = (Date)theProduct2.get(fieldName);
	                    } else if (RevRecEndDateField != null && RevRecEndDateField.contains(constants.SOBJECT_CONTRACT_COLON)){
                            string fieldName = RevRecEndDateField.subString(9, RevRecEndDateField.length());
                            endDate = (Date)theContract.get(fieldName);
	                    } 
                    }
                }
                if(Utility.checkFieldPermission(mapfieldProdRuleResult,'RevRecOpportunityLineItem__c',Constants.PERMISSION_UPSERT))
                    overrideRule.RevRecOpportunityLineItem__c = revRecId;
                if(Utility.checkFieldPermission(mapfieldProdRuleResult,'Residual_Amount__c',Constants.PERMISSION_UPSERT))
                    overrideRule.Residual_Amount__c = theRules[0].Residual_Amount__c;
                if(Utility.checkFieldPermission(mapfieldProdRuleResult,'Residual_Amount_Type__c',Constants.PERMISSION_UPSERT))
                    overrideRule.Residual_Amount_Type__c = theRules[0].Residual_Amount_Type__c;
                if(Utility.checkFieldPermission(mapfieldProdRuleResult,'initial_amount__c',Constants.PERMISSION_UPSERT))
                    overrideRule.initial_amount__c = theRules[0].initial_amount__c;
                if(Utility.checkFieldPermission(mapfieldProdRuleResult,'initial_amount_type__c',Constants.PERMISSION_UPSERT))
                    overrideRule.initial_amount_type__c = theRules[0].initial_amount_type__c;
                if(Utility.checkFieldPermission(mapfieldProdRuleResult,'Recognition_Type__c',Constants.PERMISSION_UPSERT))
                    overrideRule.Recognition_Type__c = theRules[0].Recognition_Type__c;
                if(Utility.checkFieldPermission(mapfieldProdRuleResult,'offset_type__c',Constants.PERMISSION_UPSERT))
                    overrideRule.offset_type__c  = theRules[0].offset_type__c;
                if(Utility.checkFieldPermission(mapfieldProdRuleResult,'Offset_Period__c',Constants.PERMISSION_UPSERT))
                    overrideRule.Offset_Period__c  = theRules[0].Offset_Period__c;
                if(Utility.checkFieldPermission(mapfieldProdRuleResult,'Divide_By__c',Constants.PERMISSION_UPSERT))
                    overrideRule.Divide_By__c  = theRules[0].Divide_By__c;
                if(Utility.checkFieldPermission(mapfieldProdRuleResult,'name',Constants.PERMISSION_UPSERT))
                    overrideRule.name  = '[overridden] ' + theRules[0].name ;
                if(Utility.checkFieldPermission(mapfieldProdRuleResult,'Period_or_Exact_Days__c',Constants.PERMISSION_UPSERT))
                    overrideRule.Period_or_Exact_Days__c = theRules[0].Period_or_Exact_Days__c;
                //overrideRule.Amortize_By__c = theRules[0].Amortize_By__c;
                if(Utility.checkFieldPermission(mapfieldProdRuleResult,'Milestone_Type__c',Constants.PERMISSION_UPSERT))
                    overrideRule.Milestone_Type__c = theRules[0].Milestone_Type__c;
                if(Utility.checkFieldPermission(mapfieldProdRuleResult,'Start_Percentage__c',Constants.PERMISSION_UPSERT))
                    overrideRule.Start_Percentage__c = theRules[0].Start_Percentage__c;
                if(Utility.checkFieldPermission(mapfieldProdRuleResult,'End_Percentage__c',Constants.PERMISSION_UPSERT))
                    overrideRule.End_Percentage__c = theRules[0].End_Percentage__c;
                if(Utility.checkFieldPermission(mapfieldProdRuleResult,'Is_Split_Categories__c',Constants.PERMISSION_UPSERT))
                    overrideRule.Is_Split_Categories__c = theRules[0].Is_Split_Categories__c;
                
                if(theRules[0].Recognition_Type__c == Constants.RULE_RECOGNITION_TYPE_SINGLE_TRANSACTION) {
                    if(Utility.checkFieldPermission(mapfieldProdRuleResult,'Start_Date__c',Constants.PERMISSION_UPSERT))
                        overrideRule.Start_Date__c = startDate;
                    
                    if(overrideRule.Start_Date__c == null)
                        msg = 'Start Date can not null'; 
                }else if (theRules[0].Recognition_Type__c == Constants.RULE_RECOGNITION_TYPE_AMORTIZE ||
                          theRules[0].Recognition_Type__c == Constants.RULE_RECOGNITION_TYPE_AMORTIZE_MILESTONE) {
                              
                              if(Utility.checkFieldPermission(mapfieldProdRuleResult,'Start_Date__c',Constants.PERMISSION_UPSERT))
                                  overrideRule.Start_Date__c = startDate;
                              if(Utility.checkFieldPermission(mapfieldProdRuleResult,'End_Date__c',Constants.PERMISSION_UPSERT))
                                  overrideRule.End_Date__c = endDate;
                              
                    if(overrideRule.Start_Date__c == null || overrideRule.End_Date__c == null)
                        msg = Constants.START_END_DATE_ERROR_MESSAGE;
               }
                
                if(overrideRule.End_Date__c < overrideRule.Start_Date__c)
                    msg = Constants.END_DATE_CANNOT_GREATER_ERROR_MESSAGE;
                
                //Adding values in list
                if(Utility.checkObjectPermission(Constants.PERMISSION_ACCESS, 'RevRecProductRule__c'))
                    overrideRuleToBeUpserted.add(overrideRule);
            }
        }
        if (msg.length() > 0)
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info, msg));
            
        else {
            
            //Query to fetch already existing overriden rule 
            List<RevRecProductRule__c> existingRules = [Select Id From RevRecProductRule__c Where RevRecOpportunityLineItem__c =: revRecOLIIds];
            
            //Checking for the list size and delete that rule after that creating a new one.
            if(existingRules.size() > 0 && (Utility.checkObjectPermission(Constants.PERMISSION_DELETE, 'RevRecProductRule__c')))
                delete existingRules;
        
            //Check if, list has values to update
            if(Utility.checkObjectPermission(Constants.PERMISSION_UPSERT, 'RevRecProductRule__c')){
                if(overrideRuleToBeUpserted.size() > 0)
                    upsert overrideRuleToBeUpserted;    
            }
        }
        return msg;
    }
}