temp/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>RevRecRule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RevRecRule</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>RevRecRules__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>RevRecRules__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rule_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rule Assignment</label>
        <referenceTo>Rule_Assignment__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

temp/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>RevRecRule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RevRecRule</label>
        <referenceTo>RevRecRules__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rule_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rule Assignment</label>
        <referenceTo>Rule_Assignment__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

temp/objects/Rule_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Family_Assignment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Family Assignment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <label>Product Family</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RevRecRule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RevRecRule</label>
        <referenceTo>RevRecRules__c</referenceTo>
        <relationshipLabel>Rule Assignments</relationshipLabel>
        <relationshipName>Rule_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Selected_Familys__c</fullName>
        <label>Selected Familys</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Rule Assignment</label>
    <nameField>
        <label>Rule Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rule Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Rule_Assignment_Criteria__c.object
<CustomObject>
    <fields>
        <fullName>Criteria_Field__c</fullName>
        <label>Criteria Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rule_Assignment__c</fullName>
        <label>Rule Assignment</label>
        <referenceTo>Rule_Assignment__c</referenceTo>
        <relationshipLabel>Rule Assignment Criterias</relationshipLabel>
        <relationshipName>Rule_Assignment_Criterias</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Rule Assignment Criteria</label>
    <nameField>
        <displayFormat>Rule-{0000}</displayFormat>
        <label>Rule Assignment Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Assignment Criterias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ProductTriggerHelper.cls
/**
 *  Description     :   This is the helper class for Product Trigger.
 *
 *  Created Date    :   09/06/2016
 *
 *  Created By      :   
 *
 *  Version         :   V_1.0
 *
 *  Revision Log    :   V_1.0
**/
public without  sharing class ProductTriggerHelper {
    
    //Map is used to hold the field permission
    Static Map<String, Schema.DescribeFieldResult> mapfieldOLIResult = Utility.getFieldPermissions('OpportunityLineItem');
    
    /**
     *  @description    :   This method is used to find the related Rule criteria and stamp related rule on the Product.    
     *
     *  @args           :   Trigger.New, Trigger.oldMap
     *
     *  @return         :   
    **/
    public static void assignRulesOnProducts (List<Product2> newProducts) {
        
        //Map to hold Family with Rule
        Map<String , Rule_Assignment__c> mapRuleAssignments = new Map<String , Rule_Assignment__c>();
        Map<String, String> mapRuleWithOperator = new Map<String, String>();
        
        //Query to fetch all rule assignments
        for(Rule_Assignment__c ruleAsg : [Select Id, Name, Product_Family__c, RevRecRule__c ,Selected_Familys__c,
                                          (Select Id, Operator__c , Criteria_Field__c FROM Rule_Assignment_Criterias__r 
                                          where Criteria_Field__c = 'Family' LIMIT  1) 
                                          FROM Rule_Assignment__c where
                                          Is_Family_Assignment__c = true    
                                          AND Active__c = true
                                          ORDER BY LastModifiedDate DESC]) {
            //Map rule assignments                                      
            mapRuleAssignments.put(ruleAsg.Id , ruleAsg);
            
            if(ruleAsg.Rule_Assignment_Criterias__r.size() > 0)
                mapRuleWithOperator.put(ruleAsg.Id , ruleAsg.Rule_Assignment_Criterias__r[0].Operator__c);
        }
        
        //Checking for map size
        if(mapRuleAssignments.size() > 0 && mapRuleWithOperator.size() > 0) {
              
                //Loop over Trigger.New
                for(Product2 prod : newProducts) {
                    
                    Boolean isRuleAssigned = false;
                
                    //Loop over rule assignments 
                    for(Rule_Assignment__c rule : mapRuleAssignments.values()) {
                            
                        //Boolean 
                        Boolean isRuleFound = false;
                       
                        //Checking for operator 
                        if(mapRuleWithOperator.get(rule.Id) == Constants.OPERATOR_IN) {
                            
                            //Checking for Family type
                            if(String.isNotBlank(prod.Family) && rule.Selected_Familys__c.Contains(prod.Family))
                                isRuleFound = true;
                        }
                        
                        else if (mapRuleWithOperator.get(rule.Id) == Constants.OPERATOR_NOT_IN) {
                         
                            //Checking for Family type
                            if(String.isNotBlank(prod.Family) && !rule.Selected_Familys__c.Contains(prod.Family))
                                isRuleFound = true;
                        }
                          
                    
                     //Checking if any rule found
                    if(isRuleFound && !isRuleAssigned) {
                        prod.RevRecRule__c = rule.RevRecRule__c;
                        prod.Rule_Assignment__c = rule.Id;
                        isRuleAssigned = true;
                    }
                }               
            }
        }
    }
    
    /**
    *   description     :   This method is used to calculate the date chnage dynamically related too the rule/
    *
    *   args            :
    *
    *   return          :   
    **/  
    public static void calculateDateChange(Map<Id,Product2> mapNewProducts , Map<Id, Product2> mapOldProducts) {
        
        try {
            Database.executeBatch(new Batch_UpdateOLIWithRulFromProduct(mapNewProducts.keySet(),mapNewProducts.values(),mapOldProducts), 200); 
        } catch(Exception ex) {}
    }
    
    /**
     *  @description    :   This method is used to find the related line items to the product and stamp rule over them.    
     *
     *  @args           :   Trigger.New, Trigger.oldMap
     *
     *  @return         :   
    **/
    public static void ruleAssignmentOnLineItem(Map<Id,Product2> mapNewProduct , Map<Id, Product2> mapOldProducts) {
        
        //List of line items to update
        List<OpportunityLineItem> oppLineItemsToBeUpdated = new List<OpportunityLineItem>();
        Set<Id> setProductIds = new Set<Id>();
        Set<Id> setOpportunityIds = new Set<Id>();
        String theOppId = '';
        
        //Loop over new products if rule is changed
        for(Product2 prod : mapNewProduct.values()) {
            
            if(prod.RevRecRule__c != null && mapOldProducts.get(prod.Id).RevRecRule__c == null) {
                setProductIds.add(prod.Id);
            }
        }
        
        //Check for size
        if(setProductIds.size() > 0) {
            
            //Loop over line items
            for(OpportunityLineItem oli : [SELECT Id, opportunityId, Product2Id, RevRecRule__c FROM OpportunityLineItem WHERE Product2Id IN: setProductIds AND RevRecRule__c = null]) {
                
                setOpportunityIds.add(oli.OpportunityId);
                    
                //Check if productIds are same
                if(mapNewProduct.containsKey(oli.Product2Id)) {
                    if(Utility.checkFieldPermission(mapfieldOLIResult,'RevRecRule__c',Constants.PERMISSION_UPDATE))    
                        oli.RevRecRule__c = mapNewProduct.get(oli.Product2Id).RevRecRule__c;
                    if(Utility.checkObjectPermission(Constants.PERMISSION_ACCESS, 'OpportunityLineItem'))
                        oppLineItemsToBeUpdated.add(oli);
                }
            }
        }
        
        //Check for size
        if(oppLineItemsToBeUpdated.size() > 0) {
            if(oppLineItemsToBeUpdated.size() > 20) {
                Batch_RuleAssignmentOnOLI bcMassRuleAssignmentOnOLI = new Batch_RuleAssignmentOnOLI(oppLineItemsToBeUpdated);
                DataBase.executeBatch(bcMassRuleAssignmentOnOLI,10);
            }
            else {
                if(Utility.checkObjectPermission(Constants.PERMISSION_UPDATE, 'OpportunityLineItem')){
                    update oppLineItemsToBeUpdated;
                }
            }
        }
        
        if(!Test.isRunningTest()) {
            Batch_MassOppCalculation bc = new Batch_MassOppCalculation(setOpportunityIds);
            DataBase.executeBatch(bc, 10);
        }
    }
}