temp/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>REVvue_RevRecRule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RevRecRule</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>RevRecRules__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>RevRecRules__c</referenceTo>
        <relationshipLabel>Opportunities (RevRecRule)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>REVvue_RuleAssignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rule Assignment</label>
        <referenceTo>Rule_Assignment__c</referenceTo>
        <relationshipLabel>Opportunities (Rule Assignment)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

temp/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>RevRecOpportunityLineItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RevRecOpportunityLineItem</label>
        <referenceTo>RevRecOpportunityLineItem__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RevRecRule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RevRecRule</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>RevRecRules__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>RevRecRules__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rule_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rule Assignment</label>
        <referenceTo>Rule_Assignment__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

temp/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>RevRecRule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RevRecRule</label>
        <referenceTo>RevRecRules__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rule_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rule Assignment</label>
        <referenceTo>Rule_Assignment__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

temp/objects/RevRecOpportunityLineItem__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Revenue Opportunity Line Items</relationshipLabel>
        <relationshipName>RevRecOpportunityLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RevRecRule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>REV REC RULE</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>RevRecRules__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>RevRecRules__c</referenceTo>
        <relationshipLabel>RevRecOpportunityLineItems</relationshipLabel>
        <relationshipName>RevRecOpportunityLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rule_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rule Assignment</label>
        <referenceTo>Rule_Assignment__c</referenceTo>
        <relationshipLabel>RevRecOpportunityLineItems</relationshipLabel>
        <relationshipName>RevRecOpportunityLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RevRecOpportunityLineItem</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RevRecOpportunityLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/RevRecProductRule__c.object
<CustomObject>
    <fields>
        <fullName>Divide_By__c</fullName>
        <label>Divide By</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Divided evenly between the start and end dates</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Offset_Period__c</fullName>
        <label>Offset Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Offset_Type__c</fullName>
        <label>Offset Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Start</fullName>
                </value>
                <value>
                    <fullName>Period</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Period_or_Exact_Days__c</fullName>
        <label>Period or Exact Days</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>By Period</fullName>
                </value>
                <value>
                    <fullName>By Exact Days</fullName>
                </value>
                <value>
                    <fullName>By Percentage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recognition_Type__c</fullName>
        <label>Recognition Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Residual_Amount__c</fullName>
        <label>Residual Amount:</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RevRecOpportunityLineItem__c</fullName>
        <label>RevRecOpportunityLineItem</label>
        <referenceTo>RevRecOpportunityLineItem__c</referenceTo>
        <relationshipLabel>RevRecProductRules</relationshipLabel>
        <relationshipName>RevRecProductRules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>RevRecProductRule</label>
    <nameField>
        <label>RevRecProductRule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RevRecProductRules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/RevRecRules__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Default_Rule__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default Rule</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Divide_By__c</fullName>
        <label>Divide By</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Divide Evenly Between Start and End Dates</fullName>
                </value>
                <value>
                    <fullName>Divide Evenly Between Start and End Dates - Prorate First and Last Periods</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Offset_Period__c</fullName>
        <label>Offset Period:</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Offset_Type__c</fullName>
        <label>Offset Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Start</fullName>
                </value>
                <value>
                    <fullName>Period</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recognition_Type__c</fullName>
        <label>Recognition Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Residual_Amount__c</fullName>
        <label>Residual Amount:</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>RevRecRule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RevRecRules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Rule_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Family_Assignment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Family Assignment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <label>Product Family</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RevRecRule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RevRecRule</label>
        <referenceTo>RevRecRules__c</referenceTo>
        <relationshipLabel>Rule Assignments</relationshipLabel>
        <relationshipName>Rule_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Selected_Familys__c</fullName>
        <label>Selected Familys</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Rule Assignment</label>
    <nameField>
        <label>Rule Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rule Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Rule_Assignment_Criteria__c.object
<CustomObject>
    <fields>
        <fullName>Criteria_Field__c</fullName>
        <label>Criteria Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rule_Assignment__c</fullName>
        <label>Rule Assignment</label>
        <referenceTo>Rule_Assignment__c</referenceTo>
        <relationshipLabel>Rule Assignment Criterias</relationshipLabel>
        <relationshipName>Rule_Assignment_Criterias</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Rule Assignment Criteria</label>
    <nameField>
        <displayFormat>Rule-{0000}</displayFormat>
        <label>Rule Assignment Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Assignment Criterias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ProductTriggerHelperTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
/**
 *	Description		:	This class is used to test the functionality of Trigger_Product.
 *
 *	Created Date	:
 *
 *	Version			:	V_1.0
 *
 *	Revision Log	:	V_1.0-Created
 *
 *	Coverage		:	100%
**/
@isTest(SeeAllData=false)
private class ProductTriggerHelperTest {
	
	/**
	 *	@description	:	This method is used to test product rule assignment trigger.
	**/
    static testMethod void testAssignRulesOnProducts() {
    	
        //Get standard pricbook Id to insert new price booke entery
        Id pricebookId = Test.getStandardPricebookId();   
        
        //RevRec Rule
        List<RevRecRules__c> revRecRules = new List<RevRecRules__c>();
        revRecRules.add(new RevRecRules__c(Name = 'Test-1', Active__c = true, Divide_By__c = '2',  Offset_Period__c = 2, Offset_Type__c = 'Start',
                                           Default_Rule__c = true, Recognition_Type__c = 'Amortize'));
        revRecRules.add(new RevRecRules__c(Name = 'Test-2', Active__c = true, Divide_By__c = '2',  Offset_Period__c = 2, Offset_Type__c = 'Start',
                                           Default_Rule__c = true, Recognition_Type__c = 'Single Transaction'));
        
                                                     
        insert  revRecRules;
        
    	//Rule
    	List<Rule_Assignment__c> ruleAssg = new List<Rule_Assignment__c>();
    	
    	//Add rules into list
    	ruleAssg.add(new Rule_Assignment__c(Name= 'TEST FAMILY -1' , Selected_Familys__c = 'Hardware,Software,Tax',
    										Product_Family__c = 'Hardware,Software,Tax' , Active__c = true, RevRecRule__c = revRecRules[0].Id,
    										Is_Family_Assignment__c = true));
    	
    	ruleAssg.add(new Rule_Assignment__c(Name= 'TEST FAMILY -2' , Selected_Familys__c = 'MFG',
    										Product_Family__c = 'MFG' ,Active__c = true, RevRecRule__c = revRecRules[1].Id
    										, Is_Family_Assignment__c = true));
    										
    	insert ruleAssg;
    	
    	//Rule Assignment criterais 
    	List<Rule_Assignment_Criteria__c> ruleAsgCriterias = new List<Rule_Assignment_Criteria__c>();
    	ruleAsgCriterias.add(new Rule_Assignment_Criteria__c(Criteria_Field__c = 'Family', Operator__c = 'IN' , 
    							Product_Family__c = 'Hardware,Software,Tax',Rule_Assignment__c = ruleAssg[0].Id));
    	
    	ruleAsgCriterias.add(new Rule_Assignment_Criteria__c(Criteria_Field__c = 'Family', Operator__c = 'NOT IN' , 
    							Product_Family__c = 'MFG',Rule_Assignment__c = ruleAssg[1].Id));
    	
    	insert ruleAsgCriterias;
    	
    	//List of Rule Assignment criteria
    	List<Product2> products = new List<Product2>();
    	products.add(new Product2(Name = '1Test 1' ));
    	products.add(new Product2(Name = '2Test 2' , Family = 'Tax'));
    	
    	//Test starts here 
    	Test.startTest();
    	
    	insert products;

    	//Assert for results
    	products = [Select Id , Name , RevRecRule__c, Family From Product2 Where ID IN : products ORDER BY NAME ASC];
    	System.assertEquals(2, products.size());
    	System.assertEquals(null, products[0].RevRecRule__c);
    	System.assertEquals(revRecRules[0].Id, products[1].RevRecRule__c);
    	
        //Test pricebookentry data 
        List<PricebookEntry> pricebookEntries1 = new List<PricebookEntry>();
        pricebookEntries1.add(new PricebookEntry(Pricebook2Id=pricebookId, Product2Id=products[0].id, UnitPrice=100.00, IsActive=true, UseStandardPrice=false));
        pricebookEntries1.add(new PricebookEntry(Pricebook2Id=pricebookId, Product2Id=products[1].id, UnitPrice=100.00, IsActive=true, UseStandardPrice=false));
        insert pricebookEntries1; 
        
        //Test opportunity data
        List<Opportunity> opportunities = new List<Opportunity>();
        opportunities.add(new Opportunity(Probability=100, Type='New Customer', Pricebook2Id=pricebookId, Amount=273200.00, ForecastCategoryName='Closed', name='Test Opp 1',
                                          StageName='Closed Won', CloseDate= Date.newInstance(2010, 6, 1)));
        opportunities.add(new Opportunity(Probability=100, Type='New Customer', Pricebook2Id=pricebookId, Amount=273200.00, ForecastCategoryName='Closed', name='Test Opp 1',
                                          StageName='Closed Won', CloseDate= Date.newInstance(2010, 6, 1), REVvue_RevRecRule__c = revRecRules[0].Id));    
        insert opportunities;
   
        List<Opportunity> opportunitiesToUpdate = new List<Opportunity>();
        opportunitiesToUpdate.add(new Opportunity(Id = opportunities[0].Id, REVvue_RuleAssignment__c = ruleAssg[0].Id));
        update opportunitiesToUpdate;
        
        List<RevRecOpportunityLineItem__c> rROLI = new List<RevRecOpportunityLineItem__c>();
        rROLI.add(new RevRecOpportunityLineItem__c(Name= pricebookEntries1[0].Name,  opportunity__c = opportunities[0].id));
        rROLI.add(new RevRecOpportunityLineItem__c(Name= pricebookEntries1[1].Name,  opportunity__c = opportunities[1].id));
        insert rROLI;
        
        //Test opportunity line item data
        List<OpportunityLineItem> opportunityLineItems = new List<OpportunityLineItem>();
        opportunityLineItems.add(new OpportunityLineItem(Quantity=1.00, OpportunityId=opportunities[0].id, PricebookEntryId=pricebookEntries1[0].id, UnitPrice=12000.00, RevRecOpportunityLineItem__c = rROLI[0].Id));                         
        opportunityLineItems.add(new OpportunityLineItem(Quantity=1.00, OpportunityId=opportunities[1].id, PricebookEntryId=pricebookEntries1[1].id, UnitPrice=1000.00, RevRecOpportunityLineItem__c = rROLI[1].Id));
        insert opportunityLineItems;
        
        products[0].RevRecRule__c =revRecRules[0].Id;
        update products[0];
        
        products = [Select Id , Name , RevRecRule__c, Family From Product2 Where ID IN : products ORDER BY NAME ASC];
    	System.assertEquals(2, products.size());
    	System.assertEquals(revRecRules[0].Id, products[0].RevRecRule__c);
        
        //Product override rule
        List<RevRecProductRule__c> revRecProductRules = new  List<RevRecProductRule__c>();
        revRecProductRules.add(new RevRecProductRule__c(Start_Date__c = Date.Today(), 
                                                        End_Date__c = Date.Today().addMonths(5),
                                                        Residual_Amount__c = 4000,
                                                        Offset_Period__c = 12,
                                                        Offset_Type__c = 'Start',
                                                        Divide_By__c = 'Period',
                                                        Period_or_Exact_Days__c = 'period',
                                                        RevRecOpportunityLineItem__c = rROLI[0].Id,
                                                        Recognition_Type__c = Constants.RULE_RECOGNITION_TYPE_AMORTIZE_MILESTONE,
                                                        Milestone_Type__c = 'Amount',
                                                        Revenue_Recognition_Start_Date__c = 'OPPORTUNITY:AppRopozSLN__Start_Revenue_Date__c',
                                                        Revenue_Recognition_End_Date__c = 'OPPORTUNITY:AppRopozSLN__End_Revenue_Date__c'));
        revRecProductRules.add(new RevRecProductRule__c(Start_Date__c = Date.Today(), 
                                                        End_Date__c = Date.Today(),
                                                        Residual_Amount__c = 50,
                                                        Residual_Amount_Type__c = 'Percent',
                                                        Offset_Period__c = 12,
                                                        Offset_Type__c = 'Period',
                                                        Divide_By__c = 'Period',
                                                        Period_or_Exact_Days__c = 'period',
                                                        RevRecOpportunityLineItem__c = rROLI[1].Id,
                                                        Recognition_Type__c = Constants.RULE_RECOGNITION_TYPE_AMORTIZE_MILESTONE,
                                                        Milestone_Type__c = 'Amount'));
        insert revRecProductRules;
        
        List<Product2> prodToBeUpdated = new List<Product2>();
        prodToBeUpdated.add(new Product2(Id=products[0].Id, RevRecRule__c =revRecRules[1].Id));
        update prodToBeUpdated;
        
    	//Test stop here 
    	Test.stopTest();
    }
}