temp/objects/RevRecOpportunityLineItem__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Revenue Opportunity Line Items</relationshipLabel>
        <relationshipName>RevRecOpportunityLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TotalRev__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>RevRecOpportunityLineItem</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RevRecOpportunityLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/RevRecProductRule__c.object
<CustomObject>
    <fields>
        <fullName>AM_Manual_Cal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Amortized Milestone Manual Calculation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Divide_By__c</fullName>
        <label>Divide By</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Divided evenly between the start and end dates</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Percentage__c</fullName>
        <label>End Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Initial_Amount_Type__c</fullName>
        <label>Initial Amount Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amount</fullName>
                </value>
                <value>
                    <fullName>Percent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Initial_Amount__c</fullName>
        <label>Initial Amount:</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Offset_Period__c</fullName>
        <label>Offset Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Offset_Type__c</fullName>
        <label>Offset Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Start</fullName>
                </value>
                <value>
                    <fullName>Period</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <label>Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                    <default>true</default>
                    <label>Monthly</label>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
                <value>
                    <fullName>Daily</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Period_or_Exact_Days__c</fullName>
        <label>Period or Exact Days</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>By Period</fullName>
                </value>
                <value>
                    <fullName>By Exact Days</fullName>
                </value>
                <value>
                    <fullName>By Percentage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Projected_Amount__c</fullName>
        <label>Projected Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Projected_Percent__c</fullName>
        <label>Projected Percent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Projected_Qty__c</fullName>
        <label>Projected Qty</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recognition_Type__c</fullName>
        <label>Recognition Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Residual_Amount_Type__c</fullName>
        <label>Residual Amount Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amount</fullName>
                </value>
                <value>
                    <fullName>Percent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Residual_Amount__c</fullName>
        <label>Residual Amount:</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RevRecOpportunityLineItem__c</fullName>
        <label>RevRecOpportunityLineItem</label>
        <referenceTo>RevRecOpportunityLineItem__c</referenceTo>
        <relationshipLabel>RevRecProductRules</relationshipLabel>
        <relationshipName>RevRecProductRules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Percentage__c</fullName>
        <label>Start Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>RevRecProductRule</label>
    <nameField>
        <label>RevRecProductRule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RevRecProductRules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/RevRecProductRuleMilestone__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Amount__c</fullName>
        <label>Actual Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Actual_Percent__c</fullName>
        <label>Actual Percent</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Actual_Qty__c</fullName>
        <label>Actual Qty</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Milestone_Name__c</fullName>
        <label>Milestone Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Projected_Amount__c</fullName>
        <label>Projected Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Projected_Percent__c</fullName>
        <label>Projected Percent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Projected_Qty__c</fullName>
        <label>Projected Qty</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RevRecProductRule__c</fullName>
        <label>RevRecProductRule</label>
        <referenceTo>RevRecProductRule__c</referenceTo>
        <relationshipLabel>RevRecProductRuleMilestones</relationshipLabel>
        <relationshipName>RevRecProductRuleMilestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>RevRecProductRuleMilestone</label>
    <nameField>
        <label>RevRecProductRuleMilestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RevRecProductRuleMilestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/Batch_CompareMilesAmountForManualCal.cls
/**
 *  Description     :   Batch Class to update Product Rule with AM manual calculation as true.
 *
 *  Created By      :   
 *
 *  Created Date    :   21/02/2018
 *
 *  Version         :   V1.0
 *
 *  Revision Log    :      
 *
**/
global with sharing class Batch_CompareMilesAmountForManualCal implements Database.Batchable<sObject>, Database.Stateful{

    //Start method
    global Database.QueryLocator start(Database.BatchableContext BC) {
        
        //query through the RevRecProductRules 
        return Database.getQueryLocator([SELECT Id, Offset_Period__c, Residual_Amount_Type__c, Period__c, initial_amount_type__c,
                                         Start_Date__c, Residual_Amount__c, Start_Percentage__c, End_Percentage__c,
                                         Initial_Amount__c, Divide_By__c, Period_or_Exact_Days__c,
                                         End_Date__c, RevRecOpportunityLineItem__r.TotalRev__c, Offset_Type__c, RevRecOpportunityLineItem__r.Opportunity__c
                                         FROM RevRecProductRule__c
                                         Where Recognition_Type__c = :Constants.RULE_RECOGNITION_TYPE_AMORTIZE_MILESTONE]);
    }
   
    //Execute method  
    global void execute(Database.BatchableContext BC, List<RevRecProductRule__c> productRules) {
        
        //Variables
        Double recognizableTotal = 0.0;
        Double residualTotal = 0.0;
        Double residualAmount = 0.0;
        Double initial = 0.0; 
        //Map to hold auto calculated values to be compared with existing miles
        Map<Id, Map<String, RevRecProductRuleMilestone__c>> mapToCompareProRuleIdWithMapOfMiles = new Map<Id, Map<String, RevRecProductRuleMilestone__c>>();
        //List to hold product rule to be update
        List<RevRecProductRule__c> overriddenRulesToUpdated = new List<RevRecProductRule__c>();
        RevRecUtilHelper utilHelper = new RevRecUtilHelper();
        Set<Id> setProductRuleIds = new Set<Id>();
        
        //Loop over AM type rules
        for(RevRecProductRule__c prodRule : productRules) {
            
            setProductRuleIds.add(prodRule.Id);

            if(prodRule.Residual_Amount__c != null)
                residualAmount = prodRule.Residual_Amount__c ;
            
            if (prodRule.Residual_Amount_Type__c == 'Percent') 
                residualTotal = (prodRule.RevRecOpportunityLineItem__r.TotalRev__c * residualAmount)/100.0;
            else 
                residualTotal = residualAmount;
            if(prodRule.RevRecOpportunityLineItem__r.TotalRev__c != null)
                recognizableTotal = prodRule.RevRecOpportunityLineItem__r.TotalRev__c;
            if(residualTotal != null)
                recognizableTotal -= residualTotal;
            
            Double initialAmount = (prodRule.initial_amount__c == null) ? 0 : prodRule.initial_amount__c;
            if (prodRule.initial_amount_type__c == 'Percent') 
                initial = recognizableTotal * initialAmount/100.0;
            else 
                initial = initialAmount;
        }
        
        //Map of product Id with miles of existing data
        Map<Id, List<RevRecProductRuleMilestone__c>> mapProdRuleWithExistingMilestones = new Map<Id, List<RevRecProductRuleMilestone__c>>();
        
        //Loop over miles
        for(RevRecProductRuleMilestone__c mile : [SELECT Milestone_Name__c, RevRecProductRule__c, Id, Name, Actual_Amount__c, Projected_Amount__c, Actual_Qty__c,
                                                          Projected_Qty__c, Actual_Percent__c, Projected_Percent__c
                                                          FROM RevRecProductRuleMilestone__c
                                                          WHERE RevRecProductRule__c in :setProductRuleIds]) {
            
            //Populate map
            if(!mapProdRuleWithExistingMilestones.containsKey(mile.RevRecProductRule__c))
                mapProdRuleWithExistingMilestones.put(mile.RevRecProductRule__c, new List<RevRecProductRuleMilestone__c>{mile});
            else
                mapProdRuleWithExistingMilestones.get(mile.RevRecProductRule__c).add(mile);
        }
        
        //Loop over queried data
        for(RevRecProductRule__c prodRule : productRules) {
            
            Date startDate = prodRule.Start_Date__c;
            Date endDate = prodRule.End_Date__c;
            Integer offset = 0;
            Boolean IsOffsetStart = true;  //default offset type is start, and if no offset, offset period is 0 
            String theOppId = prodRule.RevRecOpportunityLineItem__r.Opportunity__c;
            Opportunity theOppty; 
            
            if(String.isNotBlank(theOppId) && theOppId != null )            
                theOppty = (Opportunity)RevRecHelper.SelectAllFieldsForObject('Opportunity', theOppId);
                
            if (prodRule.Offset_Period__c != null) {
                if(prodRule.offset_type__c == 'Start') {
                    offset = Integer.valueOf(prodRule.Offset_Period__c);
                    IsOffsetStart = true;
                } else if (prodRule.offset_type__c == 'Period'){
                    offset = Integer.valueOf(prodRule.Offset_Period__c);
                    IsOffsetStart = false;
                }
            } 
            
            if (offset > 0) {
                if (IsOffsetStart && (startDate.addMonths(offset) < endDate)) 
                    startDate = startDate.addMonths(offset);        
                else if (!IsOffsetStart) {
                    startDate = startDate.addMonths(offset);
                    endDate = endDate.addMonths(offset);
                }
            }
            
            //Date variables
            Date lastDayOfMonth;
            Integer startDateMonth = startDate.Month();
            Integer startDateYear = startDate.Year();
            Integer endDateMonth = endDate.Month();
            Integer endDateYear = endDate.Year(); 
            Integer totalMonths = startDate.MonthsBetween(endDate);
            
            if (prodRule.Period__c == 'Monthly') {  
                
                List<Decimal> recognizableForEachMonths = new List<Decimal>();
                
                //Total months calculation
                totalMonths = utilHelper.getTotalMonths(startDate, endDate, totalMonths, prodRule);
                
                if(totalMonths == 0)
                    totalMonths =1;

                //Amount calculation
                recognizableForEachMonths = utilHelper.getRecognigibleFORAM(startDate, endDate, prodRule, (recognizableTotal-initial), totalMonths, recognizableForEachMonths, initial);

                //Miles calculation
                mapToCompareProRuleIdWithMapOfMiles = utilHelper.newMilesCalculation(recognizableForEachMonths, totalMonths, prodRule, mapToCompareProRuleIdWithMapOfMiles, startDateMonth, startDateYear, lastDayOfMonth,startDate,recognizableTotal,theOppty.Probability);
            }
        }
        
        //Compare existing and new calculated milestones
        //Loop over Existing Milestones
        for(Id productRuleId : mapProdRuleWithExistingMilestones.keySet()) {
            
            //Flag if manula update
            Boolean IsManulaUpdate = false;
            
            for(RevRecProductRuleMilestone__c miles : mapProdRuleWithExistingMilestones.get(productRuleId)) {
                if(mapToCompareProRuleIdWithMapOfMiles.get(productRuleId).containsKey(miles.Name)) {
                    
                    //Check for actuals
                    if(mapToCompareProRuleIdWithMapOfMiles.get(productRuleId).get(miles.Name).Actual_Amount__c != miles.Actual_Amount__c ||
                       mapToCompareProRuleIdWithMapOfMiles.get(productRuleId).get(miles.Name).Actual_Percent__c != miles.Actual_Percent__c ||
                       mapToCompareProRuleIdWithMapOfMiles.get(productRuleId).get(miles.Name).Actual_Qty__c != miles.Actual_Qty__c) {
                           
                           IsManulaUpdate = true;
                           break;
                    } 
                }
            }
            
            //Check if manual updates
            if(IsManulaUpdate)
                overriddenRulesToUpdated.add(new RevRecProductRule__c(Id = productRuleId, AM_Manual_Cal__c = IsManulaUpdate)); //Adding values in list to update
        }
        
        //Check if list has values to update
        if(overriddenRulesToUpdated.size() > 0) 
            update overriddenRulesToUpdated;    //DML to update product rule
    }
    
    //Finish method
    global void finish(Database.BatchableContext BC) {
    }
}