temp/objects/RevRecRuleMilestone__c.object
<CustomObject>
    <fields>
        <fullName>Milestone_Date_Source_Label__c</fullName>
        <inlineHelpText>Populate from code.</inlineHelpText>
        <label>Milestone Date Source Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Milestone_Date_Source__c</fullName>
        <inlineHelpText>Populate from code.</inlineHelpText>
        <label>Milestone Date Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RevRecRule__c</fullName>
        <label>RevRecRule</label>
        <referenceTo>RevRecRules__c</referenceTo>
        <relationshipLabel>RevRecRuleMilestones</relationshipLabel>
        <relationshipName>RevRecRuleMilestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>RevRecRuleMilestone</label>
    <nameField>
        <label>RevRecRuleMilestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RevRecRuleMilestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/objects/RevRecRules__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Default_Rule__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default Rule</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Divide_By__c</fullName>
        <label>Divide By</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Divide Evenly Between Start and End Dates</fullName>
                </value>
                <value>
                    <fullName>Divide Evenly Between Start and End Dates - Prorate First and Last Periods</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Offset_Period__c</fullName>
        <label>Offset Period:</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Offset_Type__c</fullName>
        <label>Offset Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Start</fullName>
                </value>
                <value>
                    <fullName>Period</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <label>Period:</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                    <default>true</default>
                    <label>Monthly</label>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
                <value>
                    <fullName>Daily</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recognition_Type__c</fullName>
        <label>Recognition Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>RevRecRule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RevRecRules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/classes/Batch_UpdateRuleMilestoneDateStringTest.cls
/**
 *   Purpose         :   This test class is used to test all functionality of Batch_UpdateRuleMilestoneDateString
 *               
 *   Created By      :   Bill Feehaley
 *   
 *   Created Date    :   12/20/2016
 *   
 *   Revision Logs   :   V_1.0 - Created
 *                       
 **/
@isTest(SeeAllData=false)
public class Batch_UpdateRuleMilestoneDateStringTest {

	/**
     * This method is used to test batch class
     **/
     @isTest 
     public static void testBatch_UpdateMilestoneDateString() {
        
        //Default Rule
        RevRecRules__c revRecDefaultRule = new RevRecRules__c(Name = 'Test', Active__c = true, Divide_By__c = '2',  Offset_Period__c = 2, Offset_Type__c = 'Start',
                                                              Default_Rule__c = true, Recognition_Type__c = 'Amortize', Period__c = 'Monthly');
        insert  revRecDefaultRule;
        
        //Milestone data
       	List<RevRecRuleMilestone__c>  milestones= new List<RevRecRuleMilestone__c>();
        milestones.add(new RevRecRuleMilestone__c(Milestone_Date_Source__c = 'OPPORTUNITY PRODUCT:ServiceDate' , Milestone_Date_Source_Label__c = 'OPPORTUNITY PRODUCT:ServiceDate', RevRecRule__c = revRecDefaultRule.Id));
        milestones.add(new RevRecRuleMilestone__c(Milestone_Date_Source__c = 'PRODUCT:ServiceDate' , Milestone_Date_Source_Label__c = 'PRODUCT:ServiceDate', RevRecRule__c = revRecDefaultRule.Id));
        milestones.add(new RevRecRuleMilestone__c(Milestone_Date_Source__c = 'OPPORTUNITYAppRopozSLN__End_Revenue_Date__c' , Milestone_Date_Source_Label__c = 'OPPORTUNITYAppRopozSLN__End_Revenue_Date__c', RevRecRule__c = revRecDefaultRule.Id));
        insert milestones;
         
        //Calling start method
        Test.startTest();

        //Instance of Batch_UpdateOldRuleStartAndEndDate Batch class 
        Batch_UpdateRuleMilestoneDateString ruleMilestone =new Batch_UpdateRuleMilestoneDateString();
    
        //Execute batch
        DataBase.executebatch(ruleMilestone);
        
        //Calling start method to stop batch
        Test.stopTest();
        
        //Query on Category
        milestones= [select Id, Milestone_Date_Source__c, Milestone_Date_Source_Label__c from RevRecRuleMilestone__c];
         
        System.assertEquals('OPPORTUNITY PRODUCT:ServiceDate', milestones[1].Milestone_Date_Source__c);
        System.assertEquals('OPPORTUNITY PRODUCT:ServiceDate', milestones[1].Milestone_Date_Source_Label__c);
     }    
}